pub mod ppt_project_service;
pub mod ppt_page_service;
pub mod page_element_service;
pub mod style_template_service;
pub mod ai_generation_service;
pub mod ai_edit_service;
pub mod document_parse_service;
pub mod ppt_parser;
pub mod word_parser;
pub mod pdf_parser;
pub mod markdown_parser;
pub mod text_processor;
pub mod industry_classifier;
pub mod style_consistency_engine;
pub mod style_generation_service;
pub mod style_presets;
pub mod page_generator;
pub mod content_filler;
pub mod style_applier;
pub mod ppt_exporter;
pub mod ppt_generation_service;
pub mod layout_templates;
pub mod layout_solver;
pub mod layout_engine;
pub mod prompt_extractor;
pub mod prompt_generator;
pub mod prompt_optimizer;
pub mod prompt_templates;
pub mod subscription_service;
pub mod payment_service;
pub mod credit_service;
pub mod api_key_service;
pub mod template_market_service;
pub mod template_preview;
pub mod cache_service;
pub mod progress_service;
pub mod error_handler;
pub mod performance_optimizer;
pub mod editor_handler;
pub mod analyze_handler;
pub mod content_handler;
pub mod ws_handler;

pub use ppt_project_service as s_ppt_project;
pub use ppt_page_service as s_ppt_page;
pub use page_element_service as s_page_element;
pub use style_template_service as s_style_template;
pub use ai_generation_service as s_ai_generation;
pub use ai_edit_service::{AIEditService, AIEditServiceTrait, PolishStyle, ContinueDirection, ContentLength, SummaryLength, Language, SuggestionType};
pub use document_parse_service::{DocumentParseService, DocType};
pub use ppt_parser::PptxParser;
pub use word_parser::DocxParser;
pub use pdf_parser::PdfParser;
pub use markdown_parser::MarkdownParser;
pub use style_consistency_engine::StyleConsistencyEngine;
pub use style_generation_service::StyleGenerationService;
pub use page_generator::{PageGenerator, LayoutEngine, GeneratedPage, PageElement, PageType};
pub use content_filler::ContentFiller;
pub use style_applier::StyleApplier;
pub use ppt_exporter::{PptExporter, OutputFormat, ImageFormat};
pub use ppt_generation_service::PPTGenerationService;
pub use self::layout_engine::LayoutEngine as SmartLayoutEngine;
pub use self::layout_solver::LayoutSolver;
pub use template_market_service as s_template_market;
pub use template_preview::{TemplatePreviewService, ThumbnailSize};
