//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sys_login_info")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub info_id: i64,
    pub uid: i64,
    pub user_name: String,
    pub device_type: Option<String>,
    pub ipaddr: Option<String>,
    pub login_location: Option<String>,
    pub net_work: Option<String>,
    pub browser: Option<String>,
    pub os: Option<String>,
    pub status: Option<String>,
    pub msg: Option<String>,
    pub login_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
