use crate::common::error::{Error, Result};
use crate::infrastructure::ai::config::ProviderConfig;
use crate::infrastructure::ai::types::{ImageOptions, GeneratedImage, ImageService};
use async_trait::async_trait;
use reqwest::Client;
use serde::{Deserialize, Serialize};
use std::time::Duration;

pub struct DalleService {
    config: ProviderConfig,
    client: Client,
}

impl DalleService {
    pub fn new(config: ProviderConfig) -> Result<Self> {
        let client = Client::builder()
            .timeout(Duration::from_millis(120000))
            .build()
            .map_err(|e| Error::internal_error(format!("Failed to create HTTP client: {}", e)))?;
        
        Ok(Self { config, client })
    }

    fn get_base_url(&self) -> &str {
        self.config.base_url.as_deref().unwrap_or("https://api.openai.com/v1")
    }

    fn get_size(&self, width: u32, height: u32) -> String {
        match (width, height) {
            (1024, 1024) => "1024x1024".to_string(),
            (1792, 1024) => "1792x1024".to_string(),
            (1024, 1792) => "1024x1792".to_string(),
            (512, 512) => "512x512".to_string(),
            (256, 256) => "256x256".to_string(),
            _ => {
                if width > 1024 || height > 1024 {
                    "1792x1024".to_string()
                } else {
                    "1024x1024".to_string()
                }
            }
        }
    }
}

#[async_trait]
impl ImageService for DalleService {
    async fn generate_image(&self, prompt: &str, options: ImageOptions) -> Result<GeneratedImage> {
        let url = format!("{}/images/generations", self.get_base_url());
        
        let model = options.model.as_ref().unwrap_or(&self.config.model);
        let size = self.get_size(options.width, options.height);
        
        let request_body = DalleRequest {
            model: model.clone(),
            prompt: prompt.to_string(),
            n: 1,
            size,
            quality: Some("standard".to_string()),
            response_format: Some("url".to_string()),
            style: options.style.clone(),
        };

        let response = self.client
            .post(&url)
            .header("Authorization", format!("Bearer {}", self.config.api_key))
            .header("Content-Type", "application/json")
            .json(&request_body)
            .send()
            .await
            .map_err(|e| Error::internal_error(format!("DALL-E request failed: {}", e)))?;

        if !response.status().is_success() {
            let status = response.status();
            let error_text = response.text().await.unwrap_or_default();
            return Err(Error::internal_error(format!(
                "DALL-E API error ({}): {}",
                status, error_text
            )));
        }

        let dalle_response: DalleResponse = response
            .json()
            .await
            .map_err(|e| Error::internal_error(format!("Failed to parse DALL-E response: {}", e)))?;

        let image_data = dalle_response.data
            .first()
            .ok_or_else(|| Error::internal_error("No image generated by DALL-E"))?;

        let url = image_data.url.clone()
            .ok_or_else(|| Error::internal_error("No URL in DALL-E response"))?;

        Ok(GeneratedImage::from_url(url, options.width, options.height))
    }

    async fn edit_image(&self, image: &[u8], prompt: &str, options: ImageOptions) -> Result<GeneratedImage> {
        let url = format!("{}/images/edits", self.get_base_url());
        
        let size = self.get_size(options.width, options.height);
        
        let part = reqwest::multipart::Part::bytes(image.to_vec())
            .file_name("image.png")
            .mime_str("image/png")
            .map_err(|e| Error::internal_error(format!("Failed to create multipart: {}", e)))?;

        let form = reqwest::multipart::Form::new()
            .part("image", part)
            .text("prompt", prompt.to_string())
            .text("n", "1")
            .text("size", size);

        let response = self.client
            .post(&url)
            .header("Authorization", format!("Bearer {}", self.config.api_key))
            .multipart(form)
            .send()
            .await
            .map_err(|e| Error::internal_error(format!("DALL-E edit request failed: {}", e)))?;

        if !response.status().is_success() {
            let status = response.status();
            let error_text = response.text().await.unwrap_or_default();
            return Err(Error::internal_error(format!(
                "DALL-E edit API error ({}): {}",
                status, error_text
            )));
        }

        let dalle_response: DalleResponse = response
            .json()
            .await
            .map_err(|e| Error::internal_error(format!("Failed to parse DALL-E response: {}", e)))?;

        let image_data = dalle_response.data
            .first()
            .ok_or_else(|| Error::internal_error("No image generated by DALL-E"))?;

        let url = image_data.url.clone()
            .ok_or_else(|| Error::internal_error("No URL in DALL-E response"))?;

        Ok(GeneratedImage::from_url(url, options.width, options.height))
    }

    fn provider_name(&self) -> &str {
        "dalle"
    }
}

#[derive(Debug, Serialize)]
struct DalleRequest {
    model: String,
    prompt: String,
    n: u32,
    size: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    quality: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    response_format: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    style: Option<String>,
}

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct DalleResponse {
    created: i64,
    data: Vec<DalleImageData>,
}

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct DalleImageData {
    url: Option<String>,
    #[serde(rename = "b64_json")]
    base64: Option<String>,
    revised_prompt: Option<String>,
}
