use crate::common::error::{Error, Result};
use crate::infrastructure::ai::config::ProviderConfig;
use crate::infrastructure::ai::types::{ImageOptions, GeneratedImage, ImageService};
use async_trait::async_trait;
use reqwest::Client;
use serde::{Deserialize, Serialize};
use std::time::Duration;

pub struct StabilityAI {
    config: ProviderConfig,
    client: Client,
}

impl StabilityAI {
    pub fn new(config: ProviderConfig) -> Result<Self> {
        let client = Client::builder()
            .timeout(Duration::from_millis(120000))
            .build()
            .map_err(|e| Error::internal_error(format!("Failed to create HTTP client: {}", e)))?;
        
        Ok(Self { config, client })
    }

    fn get_base_url(&self) -> &str {
        self.config.base_url.as_deref().unwrap_or("https://api.stability.ai")
    }

    fn get_engine_id(&self) -> &str {
        &self.config.model
    }
}

#[async_trait]
impl ImageService for StabilityAI {
    async fn generate_image(&self, prompt: &str, options: ImageOptions) -> Result<GeneratedImage> {
        let url = format!(
            "{}/v1/generation/{}/text-to-image",
            self.get_base_url(),
            self.get_engine_id()
        );
        
        let request_body = StabilityRequest {
            text_prompts: vec![StabilityTextPrompt {
                text: prompt.to_string(),
                weight: 1.0,
            }],
            cfg_scale: options.cfg_scale,
            height: options.height as i32,
            width: options.width as i32,
            samples: 1,
            steps: options.steps as i32,
            style_preset: options.style.clone(),
            seed: options.seed.map(|s| s as i64),
            negative_prompt: options.negative_prompt.clone().map(|np| StabilityTextPrompt {
                text: np,
                weight: -1.0,
            }).into_iter().collect(),
        };

        let response = self.client
            .post(&url)
            .header("Authorization", format!("Bearer {}", self.config.api_key))
            .header("Content-Type", "application/json")
            .header("Accept", "application/json")
            .json(&request_body)
            .send()
            .await
            .map_err(|e| Error::internal_error(format!("Stability AI request failed: {}", e)))?;

        if !response.status().is_success() {
            let status = response.status();
            let error_text = response.text().await.unwrap_or_default();
            return Err(Error::internal_error(format!(
                "Stability AI API error ({}): {}",
                status, error_text
            )));
        }

        let stability_response: StabilityResponse = response
            .json()
            .await
            .map_err(|e| Error::internal_error(format!("Failed to parse Stability AI response: {}", e)))?;

        let artifact = stability_response.artifacts
            .first()
            .ok_or_else(|| Error::internal_error("No image generated by Stability AI"))?;

        Ok(GeneratedImage::from_base64(
            artifact.base64.clone(),
            options.width,
            options.height,
            Some(artifact.content_type.clone()),
        ))
    }

    async fn edit_image(&self, image: &[u8], prompt: &str, options: ImageOptions) -> Result<GeneratedImage> {
        let url = format!(
            "{}/v1/generation/{}/image-to-image",
            self.get_base_url(),
            self.get_engine_id()
        );

        let init_image = base64::Engine::encode(&base64::engine::general_purpose::STANDARD, image);
        
        let request_body = StabilityImageToImageRequest {
            init_image,
            text_prompts: vec![StabilityTextPrompt {
                text: prompt.to_string(),
                weight: 1.0,
            }],
            cfg_scale: options.cfg_scale,
            image_strength: 0.35,
            samples: 1,
            steps: options.steps as i32,
            seed: options.seed.map(|s| s as i64),
        };

        let response = self.client
            .post(&url)
            .header("Authorization", format!("Bearer {}", self.config.api_key))
            .header("Content-Type", "application/json")
            .header("Accept", "application/json")
            .json(&request_body)
            .send()
            .await
            .map_err(|e| Error::internal_error(format!("Stability AI image-to-image request failed: {}", e)))?;

        if !response.status().is_success() {
            let status = response.status();
            let error_text = response.text().await.unwrap_or_default();
            return Err(Error::internal_error(format!(
                "Stability AI image-to-image API error ({}): {}",
                status, error_text
            )));
        }

        let stability_response: StabilityResponse = response
            .json()
            .await
            .map_err(|e| Error::internal_error(format!("Failed to parse Stability AI response: {}", e)))?;

        let artifact = stability_response.artifacts
            .first()
            .ok_or_else(|| Error::internal_error("No image generated by Stability AI"))?;

        Ok(GeneratedImage::from_base64(
            artifact.base64.clone(),
            options.width,
            options.height,
            Some(artifact.content_type.clone()),
        ))
    }

    fn provider_name(&self) -> &str {
        "stability"
    }
}

#[derive(Debug, Serialize)]
struct StabilityRequest {
    text_prompts: Vec<StabilityTextPrompt>,
    cfg_scale: f32,
    height: i32,
    width: i32,
    samples: i32,
    steps: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    style_preset: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    seed: Option<i64>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    negative_prompt: Vec<StabilityTextPrompt>,
}

#[derive(Debug, Serialize)]
struct StabilityTextPrompt {
    text: String,
    weight: f32,
}

#[derive(Debug, Serialize)]
struct StabilityImageToImageRequest {
    init_image: String,
    text_prompts: Vec<StabilityTextPrompt>,
    cfg_scale: f32,
    image_strength: f32,
    samples: i32,
    steps: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    seed: Option<i64>,
}

#[derive(Debug, Deserialize)]
struct StabilityResponse {
    artifacts: Vec<StabilityArtifact>,
}

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct StabilityArtifact {
    base64: String,
    seed: i64,
    finish_reason: String,
    content_type: String,
}
