use axum::routing::get;
use crate::api::web_path::{WebPath, WebPathType};
use crate::application::sys::*;

pub fn sys_dashboard() -> WebPath {
    WebPath::new()
        .nest(
            "/analysis",
            WebPath::new()
                .route(
                    "/total",
                    WebPathType::Get,
                    Some("获取仪表盘数据"),
                    get(s_sys_dashboard::analysis_total),
                )
                .route(
                    "/userAccessSource",
                    WebPathType::Get,
                    Some("获取仪表盘数据"),
                    get(s_sys_dashboard::user_access_source),
                )
                .route(
                    "/weeklyUserActivity",
                    WebPathType::Get,
                    Some("获取仪表盘数据"),
                    get(s_sys_dashboard::weekly_user_activity),
                )
                .route(
                    "/monthlySales",
                    WebPathType::Get,
                    Some("获取仪表盘数据"),
                    get(s_sys_dashboard::monthly_sales),
                ),
        )
        .nest(
            "/workplace",
            WebPath::new()
                .route(
                    "/total",
                    WebPathType::Get,
                    Some("获取仪表盘数据"),
                    get(s_sys_dashboard::workplace_total),
                )
                .route(
                    "/project",
                    WebPathType::Get,
                    Some("获取仪表盘数据"),
                    get(s_sys_dashboard::workplace_project),
                )
                .route(
                    "/dynamic",
                    WebPathType::Get,
                    Some("获取仪表盘数据"),
                    get(s_sys_dashboard::workplace_dynamic),
                )
                .route(
                    "/team",
                    WebPathType::Get,
                    Some("获取仪表盘数据"),
                    get(s_sys_dashboard::workplace_team),
                )
                .route(
                    "/radar",
                    WebPathType::Get,
                    Some("获取仪表盘数据"),
                    get(s_sys_dashboard::workplace_radar),
                ),
        )
}