use axum::routing::{delete, get, post, put};
use crate::api::web_path::{WebPath, WebPathType};
use crate::application::sys::*;

pub fn sys_role() -> WebPath {
    WebPath::new()
        .route(
            "/list",
            WebPathType::Get,
            Some("获取角色列表"),
            get(s_sys_role::list),
        )
        .route(
            "/menu",
            WebPathType::Get,
            Some("获取角色菜单"),
            get(s_sys_role::menu),
        )
        .route(
            "/get_role_menus",
            WebPathType::Get,
            Some("获取角色菜单"),
            get(s_sys_role::get_role_menus),
        )
        .route(
            "/get_role_depts",
            WebPathType::Get,
            Some("获取角色部门"),
            get(s_sys_role::get_role_depts),
        )
        .route(
            "/edit",
            WebPathType::Put,
            Some("编辑角色"),
            put(s_sys_role::edit),
        )
        .route(
            "/add",
            WebPathType::Post,
            Some("添加角色"),
            post(s_sys_role::add),
        )
        .route(
            "/tree",
            WebPathType::Get,
            Some("获取角色树"),
            get(s_sys_role::tree),
        )
        .route(
            "/del",
            WebPathType::Delete,
            Some("删除角色"),
            delete(s_sys_role::delete),
        )
        .route(
            "/user_role_name_list",
            WebPathType::Get,
            Some("获取用户拥有的角色名称列表"),
            get(s_sys_user_role::user_role_name_list),
        )
}

pub fn sys_role_api() -> WebPath {
    WebPath::new()
        .route(
            "/list",
            WebPathType::Get,
            Some("获取角色api列表"),
            get(s_sys_role_api::list),
        )
        .route(
            "/add",
            WebPathType::Post,
            Some("添加角色api"),
            post(s_sys_role_api::add),
        )
        .route(
            "/edit",
            WebPathType::Put,
            Some("编辑角色api"),
            put(s_sys_role_api::edit),
        )
        .route(
            "/del",
            WebPathType::Delete,
            Some("删除角色api"),
            delete(s_sys_role_api::delete),
        )
        .route(
            "/role_api_transfer_list",
            WebPathType::Get,
            Some("获取角色api所有的选择列表"),
            get(s_sys_role_api::role_api_transfer_list),
        )
        .route(
            "/add_many_role_api_transfer",
            WebPathType::Get,
            Some("添加多个角色api"),
            post(s_sys_role_api::add_many_role_api_transfer),
        )
        .route(
            "/role_permission_list",
            WebPathType::Get,
            Some("根据角色id获取api权限列表"),
            get(s_sys_role_api::role_permission_list),
        )
}