use axum::routing::{delete, get, post, put};
use crate::api::web_path::{WebPath, WebPathType};
use crate::application::sys::*;

pub fn sys_user() -> WebPath {
    WebPath::new()
        .route(
            "/list",
            WebPathType::Get,
            Some("获取用户列表"),
            get(s_sys_user::list),
        )
        .route(
            "/add",
            WebPathType::Post,
            Some("添加用户"),
            post(s_sys_user::add),
        )
        .route(
            "/edit",
            WebPathType::Put,
            Some("编辑用户"),
            put(s_sys_user::edit),
        )
        .route(
            "/depts_roles",
            WebPathType::Get,
            Some("获取用户拥有的用户部门和用户角色"),
            get(s_sys_user::depts_roles),
        )
        .route(
            "/reset_password",
            WebPathType::Put,
            Some("重置密码"),
            put(s_sys_user::reset_password),
        )
        .route(
            "/change_password",
            WebPathType::Put,
            Some("修改密码"),
            put(s_sys_user::change_password),
        )
        .route(
            "/delusers",
            WebPathType::Delete,
            Some("删除用户"),
            delete(s_sys_user::delete_users),
        )
        .route(
            "/update_avatar",
            WebPathType::Put,
            Some("更新头像"),
            put(s_sys_user::update_avatar),
        )
        .route(
            "/refersh_token",
            WebPathType::Put,
            Some("刷新token"),
            put(s_sys_user::refersh_token),
        )
        .route(
            "/login_out",
            WebPathType::Get,
            Some("用户退出"),
            get(s_sys_user::login_out),
        )
        .route(
            "/update_role_or_dept",
            WebPathType::Post,
            Some("更新用户拥有的用户部门和用户角色"),
            post(s_sys_user::update_role_or_dept),
        )
}