use axum::routing::{delete, get, post, put};
use crate::api::web_path::{WebPath, WebPathType};
use crate::api::plugin_market::plugin_market_handler as handler;

pub fn router_plugin_market() -> WebPath {
    WebPath::new().nest(
        "/plugin",
        WebPath::new()
            .route("/category/list", WebPathType::Get, Some("获取插件分类列表"), get(handler::category_list))
            .route("/category/tree", WebPathType::Get, Some("获取插件分类树"), get(handler::category_tree))
            .route("/category/:id", WebPathType::Get, Some("获取插件分类详情"), get(handler::category_detail))
            .route("/category/add", WebPathType::Post, Some("创建插件分类"), post(handler::category_create))
            .route("/category/edit", WebPathType::Put, Some("编辑插件分类"), put(handler::category_update))
            .route("/category/delete", WebPathType::Delete, Some("删除插件分类"), delete(handler::category_delete))
            .route("/market/list", WebPathType::Get, Some("获取插件市场列表"), get(handler::market_list))
            .route("/market/detail/:id", WebPathType::Get, Some("获取插件市场详情"), get(handler::market_detail))
            .route("/market/search", WebPathType::Get, Some("搜索插件"), get(handler::search))
            .route("/market/recommend", WebPathType::Get, Some("推荐插件"), get(handler::recommend))
            .route("/market/hot", WebPathType::Get, Some("热门插件"), get(handler::hot))
            .route("/market/categories", WebPathType::Get, Some("获取插件分类"), get(handler::categories))
            .route("/developer/list", WebPathType::Get, Some("开发者插件列表"), get(handler::developer_list))
            .route("/developer/add", WebPathType::Post, Some("提交插件"), post(handler::add))
            .route("/developer/edit", WebPathType::Put, Some("编辑插件"), put(handler::edit))
            .route("/developer/delete/:id", WebPathType::Delete, Some("删除插件"), delete(handler::delete_plugin))
            .route("/developer/audit", WebPathType::Put, Some("审核插件"), put(handler::audit))
            .route("/developer/version/add", WebPathType::Post, Some("发布版本"), post(handler::publish_version))
            .route("/developer/stats", WebPathType::Get, Some("销售统计"), get(handler::developer_stats))
            .route("/version/list/:plugin_id", WebPathType::Get, Some("版本列表"), get(handler::version_list))
            .route("/version/detail/:id", WebPathType::Get, Some("版本详情"), get(handler::version_detail))
            .route("/version/latest/:plugin_id", WebPathType::Get, Some("最新版本"), get(handler::latest_version))
            .route("/plan/list/:plugin_id", WebPathType::Get, Some("获取套餐列表"), get(handler::plan_list))
            .route("/plan/detail/:id", WebPathType::Get, Some("获取套餐详情"), get(handler::plan_detail))
            .route("/plan/add", WebPathType::Post, Some("创建套餐"), post(handler::plan_create))
            .route("/plan/edit", WebPathType::Put, Some("编辑套餐"), put(handler::plan_update))
            .route("/plan/delete/:id", WebPathType::Delete, Some("删除套餐"), delete(handler::plan_delete))
            .route("/cart/list", WebPathType::Get, Some("购物车列表"), get(handler::cart_list))
            .route("/cart/add", WebPathType::Post, Some("添加购物车"), post(handler::cart_add))
            .route("/cart/remove", WebPathType::Delete, Some("移除购物车"), delete(handler::cart_remove))
            .route("/cart/clear", WebPathType::Delete, Some("清空购物车"), delete(handler::cart_clear))
            .route("/order/create", WebPathType::Post, Some("创建订单"), post(handler::create_order))
            .route("/order/list", WebPathType::Get, Some("订单列表"), get(handler::order_list))
            .route("/order/detail/:id", WebPathType::Get, Some("订单详情"), get(handler::order_detail))
            .route("/order/cancel/:id", WebPathType::Post, Some("取消订单"), post(handler::cancel_order))
            .route("/order/pay/:id", WebPathType::Post, Some("发起支付"), post(handler::pay))
            .route("/order/payCallback", WebPathType::Post, Some("支付回调"), post(handler::pay_callback))
            .route("/license/list", WebPathType::Get, Some("License列表"), get(handler::license_list))
            .route("/license/detail/:id", WebPathType::Get, Some("License详情"), get(handler::license_detail))
            .route("/license/bind", WebPathType::Post, Some("绑定设备"), post(handler::bind_device))
            .route("/license/unbind", WebPathType::Post, Some("解绑设备"), post(handler::unbind_device))
            .route("/license/renew", WebPathType::Post, Some("续费License"), post(handler::renew_license))
            .route("/license/revoke", WebPathType::Post, Some("吊销License"), post(handler::revoke_license))
            .route("/license/verify", WebPathType::Post, Some("验证License"), post(handler::verify_license))
            .route("/license/heartbeat", WebPathType::Post, Some("心跳检测"), post(handler::heartbeat))
            .route("/verify/code/send", WebPathType::Post, Some("发送验证码"), post(handler::send_code))
            .route("/verify/code/check", WebPathType::Post, Some("校验验证码"), post(handler::check_code))
            .route("/verify/device/register", WebPathType::Post, Some("注册设备"), post(handler::register_device))
            .route("/verify/obfuscation/config", WebPathType::Get, Some("混淆配置"), get(handler::obfuscation_config))
            .route("/card/generate", WebPathType::Post, Some("生成卡密"), post(handler::generate_cards))
            .route("/card/batch/list", WebPathType::Get, Some("批次列表"), get(handler::card_batch_list))
            .route("/card/export/:batch_id", WebPathType::Get, Some("导出卡密"), get(handler::export_cards))
            .route("/card/redeem", WebPathType::Post, Some("兑换卡密"), post(handler::redeem_card))
            .route("/card/freeze", WebPathType::Post, Some("冻结卡密"), post(handler::freeze_card))
            .route("/card/unfreeze", WebPathType::Post, Some("解冻卡密"), post(handler::unfreeze_card))
            .route("/review/list/:plugin_id", WebPathType::Get, Some("评论列表"), get(handler::review_list))
            .route("/review/create", WebPathType::Post, Some("发表评论"), post(handler::create_review))
            .route("/review/reply", WebPathType::Post, Some("回复评论"), post(handler::reply_review))
            .route("/review/stats/:plugin_id", WebPathType::Get, Some("评论统计"), get(handler::review_stats))
            .route("/subscription/list", WebPathType::Get, Some("订阅列表"), get(handler::subscription_list))
            .route("/subscription/renew", WebPathType::Post, Some("续费订阅"), post(handler::renew_subscription))
            .route("/subscription/cancel/:id", WebPathType::Post, Some("取消订阅"), post(handler::cancel_subscription))
            .route("/developer/register", WebPathType::Post, Some("注册开发者"), post(handler::register_developer))
            .route("/developer/profile", WebPathType::Get, Some("开发者资料"), get(handler::developer_profile))
            .route("/developer/update", WebPathType::Put, Some("更新开发者资料"), put(handler::update_developer)),
    )
}