//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "cms_table_config")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub model_id: i64,
    pub name: String,
    pub code: String,
    #[sea_orm(nullable)]
    pub columns: Option<String>,
    #[sea_orm(nullable)]
    pub search: Option<String>,
    #[sea_orm(nullable)]
    pub filter: Option<String>,
    #[sea_orm(nullable)]
    pub actions: Option<String>,
    #[sea_orm(nullable)]
    pub batch_actions: Option<String>,
    #[sea_orm(nullable)]
    pub toolbar: Option<String>,
    #[sea_orm(nullable)]
    pub pagination: Option<String>,
    #[sea_orm(nullable)]
    pub features: Option<String>,
    pub is_default: String,
    pub status: String,
    #[sea_orm(nullable)]
    pub created_at: Option<DateTime>,
    #[sea_orm(nullable)]
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cms_model::Entity",
        from = "Column::ModelId",
        to = "super::cms_model::Column::Id"
    )]
    CmsModel,
}

impl Related<super::cms_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CmsModel.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
