//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "cms_form_config")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub model_id: i64,
    pub name: String,
    pub code: String,
    pub form_type: String,
    #[sea_orm(nullable)]
    pub layout: Option<String>,
    #[sea_orm(nullable)]
    pub groups: Option<String>,
    #[sea_orm(nullable)]
    pub actions: Option<String>,
    #[sea_orm(nullable)]
    pub rules: Option<String>,
    #[sea_orm(nullable)]
    pub hooks: Option<String>,
    pub is_default: String,
    pub status: String,
    #[sea_orm(nullable)]
    pub created_at: Option<DateTime>,
    #[sea_orm(nullable)]
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cms_model::Entity",
        from = "Column::ModelId",
        to = "super::cms_model::Column::Id"
    )]
    CmsModel,
}

impl Related<super::cms_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CmsModel.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
