//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "cms_field")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub model_id: i64,
    pub name: String,
    pub code: String,
    pub field_type: String,
    pub db_type: String,
    #[sea_orm(nullable)]
    pub default_value: Option<String>,
    pub is_required: String,
    pub is_unique: String,
    pub is_searchable: String,
    pub is_sortable: String,
    pub is_filterable: String,
    pub is_list_show: String,
    pub is_form_show: String,
    pub is_detail_show: String,
    #[sea_orm(nullable)]
    pub form_config: Option<String>,
    #[sea_orm(nullable)]
    pub table_config: Option<String>,
    #[sea_orm(nullable)]
    pub validation: Option<String>,
    pub sort: i32,
    #[sea_orm(nullable)]
    pub created_at: Option<DateTime>,
    #[sea_orm(nullable)]
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cms_model::Entity",
        from = "Column::ModelId",
        to = "super::cms_model::Column::Id"
    )]
    CmsModel,
}

impl Related<super::cms_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CmsModel.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
