//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "cms_tag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    #[sea_orm(nullable)]
    pub code: Option<String>,
    #[sea_orm(nullable)]
    pub slug: Option<String>,
    #[sea_orm(nullable)]
    pub color: Option<String>,
    #[sea_orm(nullable)]
    pub icon: Option<String>,
    #[sea_orm(nullable)]
    pub description: Option<String>,
    #[sea_orm(nullable)]
    pub seo_title: Option<String>,
    #[sea_orm(nullable)]
    pub seo_keywords: Option<String>,
    #[sea_orm(nullable)]
    pub seo_description: Option<String>,
    pub content_count: i64,
    pub sort: i32,
    pub status: String,
    #[sea_orm(nullable)]
    pub created_at: Option<DateTime>,
    #[sea_orm(nullable)]
    pub updated_at: Option<DateTime>,
    #[sea_orm(nullable)]
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cms_content_tag::Entity")]
    CmsContentTag,
}

impl Related<super::cms_content_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CmsContentTag.def()
    }
}

impl Related<super::cms_content::Entity> for Entity {
    fn to() -> RelationDef {
        super::cms_content_tag::Relation::CmsContent.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::cms_content_tag::Relation::CmsTag.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
