//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "cms_category")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub parent_id: i64,
    #[sea_orm(nullable)]
    pub model_id: Option<i64>,
    pub name: String,
    #[sea_orm(nullable)]
    pub code: Option<String>,
    #[sea_orm(nullable)]
    pub slug: Option<String>,
    #[sea_orm(nullable)]
    pub icon: Option<String>,
    #[sea_orm(nullable)]
    pub image: Option<String>,
    #[sea_orm(nullable)]
    pub description: Option<String>,
    #[sea_orm(nullable)]
    pub keywords: Option<String>,
    #[sea_orm(nullable)]
    pub template_list: Option<String>,
    #[sea_orm(nullable)]
    pub template_detail: Option<String>,
    pub page_size: i32,
    pub sort: i32,
    pub status: String,
    #[sea_orm(nullable)]
    pub seo_title: Option<String>,
    #[sea_orm(nullable)]
    pub seo_keywords: Option<String>,
    #[sea_orm(nullable)]
    pub seo_description: Option<String>,
    #[sea_orm(nullable)]
    pub created_at: Option<DateTime>,
    #[sea_orm(nullable)]
    pub updated_at: Option<DateTime>,
    #[sea_orm(nullable)]
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cms_model::Entity",
        from = "Column::ModelId",
        to = "super::cms_model::Column::Id"
    )]
    CmsModel,
    #[sea_orm(has_many = "super::cms_content::Entity")]
    CmsContent,
}

impl Related<super::cms_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CmsModel.def()
    }
}

impl Related<super::cms_content::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CmsContent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
