//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "cms_model")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub code: String,
    pub table_name: String,
    #[sea_orm(nullable)]
    pub description: Option<String>,
    #[sea_orm(nullable)]
    pub icon: Option<String>,
    #[sea_orm(nullable)]
    pub category_id: Option<i64>,
    pub is_system: String,
    pub is_enabled: String,
    pub sort: i32,
    #[sea_orm(nullable)]
    pub config: Option<String>,
    #[sea_orm(nullable)]
    pub created_at: Option<DateTime>,
    #[sea_orm(nullable)]
    pub updated_at: Option<DateTime>,
    #[sea_orm(nullable)]
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cms_field::Entity")]
    CmsField,
    #[sea_orm(has_many = "super::cms_content::Entity")]
    CmsContent,
    #[sea_orm(has_many = "super::cms_category::Entity")]
    CmsCategory,
    #[sea_orm(has_many = "super::cms_form_config::Entity")]
    CmsFormConfig,
    #[sea_orm(has_many = "super::cms_table_config::Entity")]
    CmsTableConfig,
    #[sea_orm(has_many = "super::cms_code_gen::Entity")]
    CmsCodeGen,
}

impl Related<super::cms_field::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CmsField.def()
    }
}

impl Related<super::cms_content::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CmsContent.def()
    }
}

impl Related<super::cms_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CmsCategory.def()
    }
}

impl Related<super::cms_form_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CmsFormConfig.def()
    }
}

impl Related<super::cms_table_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CmsTableConfig.def()
    }
}

impl Related<super::cms_code_gen::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CmsCodeGen.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
