//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "cms_content_tag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub content_id: i64,
    pub tag_id: i64,
    #[sea_orm(nullable)]
    pub created_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cms_content::Entity",
        from = "Column::ContentId",
        to = "super::cms_content::Column::Id"
    )]
    CmsContent,
    #[sea_orm(
        belongs_to = "super::cms_tag::Entity",
        from = "Column::TagId",
        to = "super::cms_tag::Column::Id"
    )]
    CmsTag,
}

impl Related<super::cms_content::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CmsContent.def()
    }
}

impl Related<super::cms_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CmsTag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
