//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "cms_content")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub model_id: i64,
    #[sea_orm(nullable)]
    pub category_id: Option<i64>,
    pub title: String,
    #[sea_orm(nullable)]
    pub slug: Option<String>,
    #[sea_orm(nullable)]
    pub keywords: Option<String>,
    #[sea_orm(nullable)]
    pub description: Option<String>,
    #[sea_orm(nullable)]
    pub author_id: Option<i64>,
    #[sea_orm(nullable)]
    pub source: Option<String>,
    #[sea_orm(nullable)]
    pub thumbnail: Option<String>,
    #[sea_orm(nullable)]
    pub images: Option<String>,
    #[sea_orm(nullable)]
    pub attachments: Option<String>,
    pub content_type: String,
    pub status: String,
    #[sea_orm(nullable)]
    pub publish_time: Option<DateTime>,
    #[sea_orm(nullable)]
    pub expire_time: Option<DateTime>,
    pub sort: i32,
    pub view_count: i64,
    pub like_count: i64,
    pub comment_count: i64,
    pub is_top: String,
    pub is_recommend: String,
    pub is_hot: String,
    pub allow_comment: String,
    #[sea_orm(nullable)]
    pub password: Option<String>,
    #[sea_orm(nullable)]
    pub template: Option<String>,
    #[sea_orm(nullable)]
    pub extra_data: Option<String>,
    #[sea_orm(nullable)]
    pub created_at: Option<DateTime>,
    #[sea_orm(nullable)]
    pub updated_at: Option<DateTime>,
    #[sea_orm(nullable)]
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cms_model::Entity",
        from = "Column::ModelId",
        to = "super::cms_model::Column::Id"
    )]
    CmsModel,
    #[sea_orm(
        belongs_to = "super::cms_category::Entity",
        from = "Column::CategoryId",
        to = "super::cms_category::Column::Id"
    )]
    CmsCategory,
    #[sea_orm(has_many = "super::cms_content_tag::Entity")]
    CmsContentTag,
    #[sea_orm(has_many = "super::cms_content_version::Entity")]
    CmsContentVersion,
}

impl Related<super::cms_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CmsModel.def()
    }
}

impl Related<super::cms_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CmsCategory.def()
    }
}

impl Related<super::cms_content_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CmsContentTag.def()
    }
}

impl Related<super::cms_content_version::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CmsContentVersion.def()
    }
}

impl Related<super::cms_tag::Entity> for Entity {
    fn to() -> RelationDef {
        super::cms_content_tag::Relation::CmsTag.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::cms_content_tag::Relation::CmsContent.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
