//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod c_consumer;
pub mod c_login_log;
pub mod c_sms_log;
pub mod c_payment_order;
pub mod c_finance_account;
pub mod c_finance_transaction;
pub mod c_media_file;
pub mod c_logistics_tracking;
pub mod c_freight_template;
pub mod c_user_oauth;
pub mod c_user_level_config;
pub mod c_user_level;
pub mod c_user_level_record;
pub mod c_user_tag;
pub mod c_user_tag_relation;
pub mod c_user_ban;
pub mod c_consumer_statistics;

pub mod c_after_sale;
pub mod c_after_sale_item;
pub mod c_after_sale_refund;
pub mod c_after_sale_logistics;
pub mod c_after_sale_status_log;
pub mod c_after_sale_timeout_config;

pub mod c_wechat_mp_config;
pub mod c_wechat_mini_config;
pub mod c_sms_config;
pub mod c_sms_template;
pub mod c_oss_config;
pub mod c_logistics_company;

pub mod pay_channel;

pub mod sys_api_permission;
pub mod sys_dept;
pub mod sys_dict_data;
pub mod sys_dict_type;
pub mod sys_job;
pub mod sys_job_log;
pub mod sys_login_info;
pub mod sys_menu;
pub mod sys_notice;
pub mod sys_oper_log;
pub mod sys_post;
pub mod sys_role;
pub mod sys_role_api;
pub mod sys_role_dept;
pub mod sys_role_menu;
pub mod sys_user;
pub mod sys_user_dept;
pub mod sys_user_post;
pub mod sys_user_role;
pub mod sys_white_jwt;

pub mod p_category;
pub mod p_brand;
pub mod p_product;
pub mod p_product_group;
pub mod p_product_group_relation;
pub mod p_product_category;
pub mod p_spec;
pub mod p_spec_value;
pub mod p_sku;
pub mod p_stock_log;
pub mod p_stock_alert;
pub mod p_shipping_template;
pub mod p_shipping_template_region;
pub mod p_store;
pub mod p_store_stock;
pub mod p_verification_log;
pub mod p_attribute_template;
pub mod p_attribute;
pub mod p_attribute_value;
pub mod p_product_attribute;

// Plugin Market Entities
pub mod p_plugin;
pub mod p_plugin_version;
pub mod p_plugin_category;
pub mod p_plugin_review;
pub mod p_plugin_verification_code;
pub mod p_plan;
pub mod p_order;
pub mod p_cart;
pub mod p_subscription;
pub mod p_license;
pub mod p_device;
pub mod p_card;
pub mod p_card_batch;
pub mod p_developer;
pub mod p_verification_code;

// CMS Entities
pub mod cms_model;
pub mod cms_field;
pub mod cms_content;
pub mod cms_content_tag;
pub mod cms_content_version;
pub mod cms_category;
pub mod cms_tag;
pub mod cms_form_config;
pub mod cms_table_config;
pub mod cms_code_gen;
