//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sys_dept")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub dept_id: i64,
    pub parent_id: i64,
    pub dept_name: Option<String>,
    pub lft: i32,
    pub rgt: i32,
    pub depth: i32,
    pub dept_category: Option<String>,
    pub order: i32,
    pub leader: Option<i64>,
    pub phone: Option<String>,
    pub email: Option<String>,
    pub status: String,
    pub remark: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sys_role_dept::Entity")]
    SysRoleDept,
    #[sea_orm(has_many = "super::sys_user_dept::Entity")]
    SysUserDept,
}

impl Related<super::sys_role_dept::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SysRoleDept.def()
    }
}

impl Related<super::sys_user_dept::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SysUserDept.def()
    }
}

impl Related<super::sys_role::Entity> for Entity {
    fn to() -> RelationDef {
        super::sys_role_dept::Relation::SysRole.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::sys_role_dept::Relation::SysDept.def().rev())
    }
}

impl Related<super::sys_user::Entity> for Entity {
    fn to() -> RelationDef {
        super::sys_user_dept::Relation::SysUser.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::sys_user_dept::Relation::SysDept.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
