//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sys_white_jwt")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub jid: i64,
    pub uid: i64,
    pub token_id: i64,
    pub info_id: i64,
    pub token_expr: i64,
    pub created_at: DateTime,
    pub update_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
