//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sys_job_log")]
pub struct Model {
    pub created_at: DateTime,
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub id: i64,
    pub job_id: i64,
    pub run_count: i32,
    pub job_message: Option<String>,
    pub status: String,
    pub elapsed_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
