//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sys_notice")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub notice_id: i64,
    pub notice_title: String,
    pub notice_type: String,
    #[sea_orm(column_type = "custom(\"longblob\")", nullable)]
    pub notice_content: Option<String>,
    pub status: Option<String>,
    pub create_dept: Option<i64>,
    pub create_by: Option<i64>,
    pub created_at: Option<DateTime>,
    pub update_by: Option<i64>,
    pub updated_at: Option<DateTime>,
    pub remark: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
